version: '3.8'
services:
  app:
    extends:
      file: docker-compose-eureka-server-base.yml
      service: app
    container_name: eureka-server-staging
    ports:
      - "8115:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=staging
      - TAG=v1.0.0-staging
    networks:
      - nervus-infrastructure_default

networks:
  nervus-infrastructure_default:
    external: true